wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1676926621.206719
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.13.10
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 5
hidden_layers:
  desc: null
  value:
  - 64
  - 64
learning_rate:
  desc: null
  value: 0.001
replay_batch_num:
  desc: null
  value: 4
variant:
  desc: null
  value: duel
